name: chrome build test
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Cypress run on Chrome
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headed: true