name: Parallel build test
on: push
jobs:
  Add-to-cart-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:addToCart
      - name: HTML Mochawesome Test Report
        uses: actions/upload-artifact@v4
        with:
        name: AddtoCart report
        path: cypress/reports/html
  
  Register-flow-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:registerflow
      
      - name: HTML Mochawesome Test Report
        uses: actions/upload-artifact@v4
        with:
        name: Reg flow report
        path: cypress/reports/html